### PR TITLE
Finish markdown preview, update page UI

### LINKED ISSUE #65: Note Page: Render Markdown
**Description of problem/updates:** Like on GitHub, we should have a tab to switch between Write/Preview. Writing should be a textbox with plaintext in it, and Preview should show the stylized Markdown.
To do this, we need to be able to convert our Markdown to HTML and display that under the Preview tab.
Possible Solution:
- https://github.com/showdownjs/showdown
Screen Shot 2022-11-18 at 6 31 56 PM

### PR DESCRIPTION
**Pull request by alexzhang1618**
- Add markdown rendering for individual note pages
- Add/modify view, edit, save, and delete note buttons
- Move page buttons to the top of the screen 
- Restyle page
- Add deployed website URL to the main README
- Closes #65 

View page
Screen Shot 2022-11-27 at 10 22 01 PM
Edit page
Screen Shot 2022-11-27 at 10 22 17 PM
Blank note
Screen Shot 2022-11-27 at 11 24 31 PM

### CODE REVIEW

**Review by greyluo — COMMENTED** [review]
Looks awesome! 
Do you think if it'd be a better idea to allow users to switch between normal editing and markdown? Because for those who don't know anything about markdown, the text styling might be confusing like making a new line or spacing. It might not be a button but at least some way to tell users that they are in markdown mode.

**Comment by alexzhang1618** [comment]
Just added a placeholder for the content area so users can tell that Markdown is supported

**Review by laurenkiyomi — APPROVED** [review]

**Review by laurenkiyomi — CHANGES_REQUESTED** [review]
For me, the title of the note is still editable even when I'm in view mode.

Also, when first creating a note I think it might be better if view note and delete note are not shown? Because we haven't created the note until the save button is clicked the first time, so why would we be able to delete the note?

Also, why is "save note" an option in view mode?

Bug: When I click New Note and hit save 3 times in a row, it creates 3 new notes. I think we should be put in view mode once we click save after creating the note.

**Comment by alexzhang1618** [comment]
- Fixed styling changes
- Switch to view mode after saving note
- I left the buttons in on both modes because I think it's less intuitive if buttons appear/disappear without clear explanation why
  - For a new note, the delete button returns you to the dashboard
  - The view button is also useful for new notes because they may want to see what the markdown preview looks like before saving

**Review by laurenkiyomi — APPROVED** [review]

**Pull request merged**
